### PR TITLE
refactor: removes a redundant return statement

### LINKED ISSUE #783: Remove this redundant jump.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLzdi9mf_H5ePyyO&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLzdi9mf_H5ePyyO&tab=code

### PR DESCRIPTION
**Pull request by syedzubeen**
**Description**

Changes proposed in this pull request:

Removed a redundant return statement

**Related issue(s)**
Fixes #783

### CODE REVIEW

**Comment by derberg** [comment]
@syedzubeen Thanks for the PR. When you contribute to any project, especially open source, you should open a PR only once you are familiarized with contributing guide like https://github.com/asyncapi/asyncapi-react/blob/master/CONTRIBUTING.md

- please adjust your PR title:
   - use [imperative mood](https://cbea.ms/git-commit/#imperative) in PR title
   - use proper conventional commits prefix (you have a bot comment with details - in your case it is `refactor`

**Comment by syedzubeen** [comment]
Done !

**Comment by derberg** [comment]
test fails for the same reason as described in https://github.com/asyncapi/asyncapi-react/pull/807#pullrequestreview-1663107954

**Comment by derberg** [comment]
closing as not clear how to fix it

**Pull request closed without merging**
