### PR TITLE
feat: make @asyncapi/react-component compatible with vs-asyncapi-preview

### PR DESCRIPTION
**Pull request by catosaurusrex2003**
**Description**
I merged `library/src/containers/AsyncApi/AsyncApi.tsx` and `library/src/containers/AsyncApi/Standalone.tsx` functionality into `library/src/containers/AsyncApi/Standalone.tsx`

This pr will **not** cause any change/improvement in the working of `playground` or `@asyncapi/react-component`.
It wil improve `vs-asyncapi-preview` and will make the error to render as expected.

Before:
image

After:
image

**Related issue(s)**
solves the issue #1077
and 
[https://github.com/asyncapi/vs-asyncapi-preview/issues/200](https://github.com/asyncapi/vs-asyncapi-preview/issues/200)

### CODE REVIEW

**Comment by AceTheCreator** [comment]
@catosaurusrex2003 Did you check to ensure it doesn't break the web-component?

**Comment by catosaurusrex2003** [comment]
@AceTheCreator Thanks for pointing that out! I missed that check. I'll review it and get back to you shortly.

**Comment by catosaurusrex2003** [comment]
@AceTheCreator `web-component` is working

image

(The title is not showing though)
Below is the html in which i used the locally symlinked `web-component` and `react-component`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <!-- Load the webcomponents polyfill if targeting older browsers -->
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.5.0/webcomponents-bundle.js"></script>

    <script
      type="module"
      src="./node_modules/@asyncapi/web-component/lib/asyncapi-web-component.js"
      defer
    ></script>

    <asyncapi-component
      schemaUrl="./asyncapi.yml"
      config='{"show": {"info": false}}'
      schemaFetchOptions='{"method":"GET","mode":"cors"}'
      cssImportPath="./node_modules/@asyncapi/react-component/styles/default.min.css"
    >
    </asyncapi-component>
  </body>
</html>

```

`@asyncapi/react-component` also work for [standalone](https://github.com/asyncapi/asyncapi-react/blob/master/docs/usage/standalone-bundle.md)

I also checked [using it in nextjs](https://github.com/asyncapi/asyncapi-react/blob/master/docs/usage/nextjs.md)
and it is working fine
image
image

should i test in [angular](https://github.com/asyncapi/asyncapi-react/blob/master/docs/usage/angular.md), [vue](https://github.com/asyncapi/asyncapi-react/blob/master/docs/usage/vue.md).
If yes then this is gonna take time because i am not familiar with these frameworks.

**Comment by catosaurusrex2003** [comment]
yes that seems to be the reason

**Comment by catosaurusrex2003** [comment]
@AceTheCreator am i missing something in scope of this library. Like somewhere this library is used and my changes might break it.
One thing i noticed is that these changes might make Studio slower and more laggy, as the document is parsed more than once times.

**Comment by AceTheCreator** [comment]
> @AceTheCreator am i missing something in scope of this library. Like somewhere this library is used and my changes might break it. One thing i noticed is that these changes might make Studio slower and more laggy, as the document is parsed more than once times.

Exactly what i thought, currently working on a possible fix, i'll ping.

**Comment by catosaurusrex2003** [comment]
I’d like to discard this PR as I realize I've made the solution more complicated than necessary. 

The simpler solution can be found in PR #1082. 

I should have taken more time to think through my approach before coding. @AceTheCreator

**Pull request closed without merging**
