### PR TITLE
feat: render bindings in relevant sections

### PR DESCRIPTION
**Pull request by 195858**
**Description**

Changes proposed in this pull request:

- Created a new bindings/binding component
-  Added styles for the new component
- Updated the types to include bindings in the appropriate interfaces
- Updated server, channel, operation and message components
to render bindings if present
- Slightly changed operation/messages rendering

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@195858 Hi! Thanks for contribution! I will do a review by Friday at the latest :)

**Comment by 195858** [comment]
Thanks, when reviewing the changes you will realise I adjusted the way operations and its messages are rendered in a channel. The reason for that was that the "RawMessage" case for an operation (as opposed of having multiple messages associated) wasn't rendered that clearly and it was hard to figure out what's what in case there's a publish and subscribe operation with a single (RawMessage) option only.

**Comment by derberg** [comment]
@195858 please update this PR by extending the streetlight example with bindings on all possible levels (the spec that is loaded by default in the playground). We always try to extend those example to show new features in action out-of-the-box

**Comment by 195858** [comment]
@derberg - streetlights spec update should now show in the pull request.

**Comment by 195858** [comment]
I just realised there are cases my changes don't handle - nested properties and SchemaObject propeerties.
I'll submit another PR once it's fixed.

**Comment by magicmatatjahu** [comment]
@195858 Don't worry, If you have any problems, please ping us on the Slack :)

**Pull request closed without merging**
