### PR TITLE
refactor: remove the unexpected empty blocks

### LINKED ISSUE #787: Unexpected empty block
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnL27i9mf_H5ePyyT&tab=why

## Where's the issue? 
- https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=12
-   https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=19
- https://sonarcloud.io/code?id=asyncapi_asyncapi-react&selected=asyncapi_asyncapi-react%3Alibrary%2Fsrc%2Fstyles%2Fdefault.css&line=60

### PR DESCRIPTION
**Pull request by parasss19**
**Description**

Changes proposed in this pull request:

- Removed some unexpected empty blocks from the path library/src/styles/default.css

**Related issue(s)**
fixes #787

### CODE REVIEW

**Comment by parasss19** [comment]
hey @derberg Please review it
Also provide labels like hacktoberfest2023, hacktoberfest-accepted on issues and my pr so that it would be accepted in hacktoberfest

**Comment by derberg** [comment]
no need for a label, repo has a proper topic already

Screenshot 2023-10-04 at 11 20 14

**Comment by derberg** [comment]
I also changed the prefix of the PR as we do not need to release a fix, it is simple refactor that has no result on produced library, just a cleanup

**Review by derberg — APPROVED** [review]
Thanks, happy Hacktoberfest 🍺

**Pull request merged**
