### PR TITLE
Fix tab navigation issue in Tab component

### PR DESCRIPTION
**Pull request by NEMYSESx**
Fixes: #1008
The condition in the onClick handler of TabLink has been fixed.

### CODE REVIEW

**Comment by NEMYSESx** [comment]
Hey!! Can you review the code and merge it plz
 It's my first open source contribution. My confidence will boost if u consider reviewing it

**Comment by ibishal** [comment]
> Hey!! Can you review the code and merge it plz It's my first open source contribution. My confidence will boost if u consider reviewing it

@NEMYSESx follow the PR naming conventions[here](https://github.com/asyncapi/asyncapi-react/pull/1024#issuecomment-2197822041), in your case add a `fix:` in start of your PR name

**Comment by Gmin2** [comment]
Dont push the `package-lock.json` file in the PR, and please include a video showing the issue resolved

**Comment by ibishal** [comment]
Dont push the `package-lock.json` in the PR, and if you can also include a video of the working solution

**Comment by derberg** [comment]
closing as there is no response and PR quality is anyway far from following basic requirements

**Pull request closed without merging**
