### PR TITLE
fix: refresh state in playground by debounce

### LINKED ISSUE #200: Fixed RefreshIcon location
**Description**
Set the refresh icon (on https://asyncapi.github.io/asyncapi-react/) to a fixed location so it's still visible when scrolling through YAML content on left hand pane.

**Reasons**
When debugging a large AsyncAPI document (few hundred lines+), manually scrolling to the top of the page each time to trigger an update is somewhat tedious. Having the refresh icon in a fixed location that's always visible regardless of scrolling would avoid this.

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:

- More info: https://github.com/asyncapi/asyncapi-react/issues/200
- Add `debounce` when user input new data in schema editor - after 750ms new view should be rendered with updated schema.
- Show refresh icon with spin animation when schema or config is updating.

> NOTE: `fix` is only added due to automatically push new playground.

New look:
image

**Related issue(s)**
Resolves #200

### CODE REVIEW

**Comment by derberg** [comment]
@magicmatatjahu refresh button is still there because of configuration? shouldn't it be visible only when you switch to configuration tab?

**Comment by magicmatatjahu** [comment]
@derberg I left it because someone would like refresh manually state, but I find weird bug with memory allocation so I will remove icon as well.

**Comment by magicmatatjahu** [comment]
@derberg I think everything should be done.

**Review by derberg — APPROVED** [review]
:shipit:

**Review by fmvilas — APPROVED** [review]

**Pull request merged**
