### PR TITLE
refactor: switch to parser-js in most places 

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

> if someone think that the PR is too big, I will try to divide the PR into two smaller ones.

Changes proposed in this pull request:
- Switch to `parser-js` in `Info`, `Servers` (also in single `Server`), `Channels` (also in single `Channel`), `Messages` (also in single `Message`), `Schemas` components,
- left single `Schema` component, because it is the most complicated component in package and it should be rewritten with https://github.com/asyncapi/shape-up-process/issues/87 task - also by this I left some code related to "beautify" our schema - if `Schema` component will be rewritten, we will remove about leftover 10-15% of code.
- I wanna treat PR as chore, because I wanna merge to `unify-component` branch :)

**Related issue(s)**
Part of https://github.com/asyncapi/shape-up-process/issues/85

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]
Great stuff, Maciej! 👏

**Comment by fmvilas** [comment]
BTW, I think the [beautifying process](https://github.com/asyncapi/asyncapi-react/blob/master/library/src/helpers/beautifier.ts) should be removed entirely. Not on this PR but at some point during the cycle. As it is right now, there are a couple of things that are not needed or incorrect:

* Resolving `allOf`: this is incorrect, we're treating `allOf` as merging objects and that's not the correct behavior.
* Rendering Markdown can be done using a React Markdown component.

**Comment by magicmatatjahu** [comment]
@fmvilas

> BTW, I think the beautifying process should be removed entirely. Not on this PR but at some point during the cycle. As it is right now, there are a couple of things that are not needed or incorrect:
>
> Resolving allOf: this is incorrect, we're treating allOf as merging objects and that's not the correct behavior.
Rendering Markdown can be done using a React Markdown component.

I mention about removing this process in sentence:

> ...also by this I left some code related to "beautify" our schema - if Schema component will be rewritten, we will remove about leftover 10-15% of code.

I used React Markdown component in previous job and it's awesome, but this is a nice-to-have feature in unification :) We can stay with `markdown-it` library used here https://github.com/asyncapi/asyncapi-react/blob/master/library/src/helpers/renderMarkdown.tsx

**Comment by derberg** [comment]
@magicmatatjahu I would just change commit scope to `refactor:` and :shipit:

**Comment by magicmatatjahu** [comment]
@derberg Done :)

**Review by derberg — APPROVED** [review]

**Pull request merged**
