### PR TITLE
ci: publish playground from next branch

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:

- publish playground from `next` branch - update appropriate workflow for that
- improve showing errors from parser: break the words

Errors:
image

**Related issue(s)**
Part of https://github.com/asyncapi/asyncapi-react/issues/300

### CODE REVIEW

**Review by derberg — CHANGES_REQUESTED** [review]
correct me if I'm wrong, but this PR introduces features and fixes for 3 totally unrelated topics, right?

- update of openapi-sampler should be a separate PR to master and merged as `feat: ` with a proper description of what else is added with their first major version of openapi-sampler, as it is purely not only because of `time` format
- fix of errors should also go to master

above can be then pulled into `next`

and last but not least is a PR to `next` with circular refs support for items as this is a part of the release candidate for major version.

**Comment by magicmatatjahu** [comment]
@derberg Thanks for the review!

> update of openapi-sampler should be a separate PR to master and merged as feat: with a proper description of what else is added with their first major version of openapi-sampler, as it is purely not only because of time format

Ok, I will create a PR for that. There is also supporting for `draft-07` of JSON Schema and supports fo other formats than `time`.

> fix of errors should also go to master
> above can be then pulled into next

It cannot be done, and then pulled, because code for displaying errors is different in `next` and `master` branches, it's not only related code itself, but also for different styling `fiori` and `tailwind`. We cannot reconcile it.

TBH I don't think so that we should split those changes to 3 separates PRs, then it's is an art for art, but ok, I will create it.

**Comment by magicmatatjahu** [comment]
In addition, errors from parser has been displaying on the master for a long time, I just want to close one issue, because I fixed some styles displaying errors -> little change https://github.com/asyncapi/asyncapi-react/pull/352/files#diff-18b2a4882a0019cfc814b13ccea23aeaf24e1835040ea9912df58f980043aa0cR19 so I don't think so that we should split this change to separate PR.

**Comment by derberg** [comment]
@magicmatatjahu not really art for art, it is just cleaner and by pushing openapi-sampler to master you make the feature available to others long weeks before major version of the component is available, it is worth it. As for the errors, I agree that if it is going to be to complex later to pull it into next, then let us not put it into master

**Comment by magicmatatjahu** [comment]
> not really art for art, it is just cleaner and by pushing openapi-sampler to master you make the feature available to others long weeks before major version of the component is available, it is worth i

About `art for art` was related to splitting PRs to 3 separate for next :P I agree with bumping package also in master.

**Comment by derberg** [comment]
> About art for art was related to splitting PRs to 3 separate

if you want to have a quick review, then it is not art 🤷🏼 
just look at what you've done here -> https://github.com/asyncapi/asyncapi-react/pull/356. This is just beautiful dude, one file changed, PR focused on one thing, I do not have to spend too much time on figuring out what changes is related to what 1 of 3 issues 🤷🏼 it is art for me, but a positive art, I hope you see it 😄

**Review by derberg — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@derberg Thanks a lot!

**Pull request merged**
