### PR TITLE
fix: external link will open in the same window

### PR DESCRIPTION
**Pull request by ItshMoh**
Now the external link will open in the same window.

**Description**

**Related issue(s)**
#962 
[video](https://www.loom.com/share/a4d6280fb6564479b6204c12c0fcf2ea?sid=5f0cc668-4335-431d-966e-4d6b7a2ccee2)

### CODE REVIEW

**Review by DhairyaMajmudar — APPROVED** [review]
Looks Good 🚀

**Comment by AceTheCreator** [comment]
@ItshMoh, i don't think external link should open in the same window, instead we should let users know it opens a new window as indicated in the issue :)

**Review by AceTheCreator — CHANGES_REQUESTED** [review]
@ItshMoh, i don't think external link should open in the same window, instead we should let users know it opens a new window as indicated in the issue :)

**Comment by ItshMoh** [comment]
> @ItshMoh, i don't think external link should open in the same window, instead we should let users know it opens a new window as indicated in the issue :)

Hey @AceTheCreator Do you want the message for opening to the new window like this. 
alert_new_window_react
Here when user clicks the link it will get alert notifcations.

**Comment by AceTheCreator** [comment]
> > @ItshMoh, i don't think external link should open in the same window, instead we should let users know it opens a new window as indicated in the issue :)
> 
> Hey @AceTheCreator Do you want the message for opening to the new window like this. alert_new_window_react Here when user clicks the link it will get alert notifcations.

@ItshMoh, it doesn't have to be an alert, you can just add the warning message inside the title attribute like this:

<a href="https://example.com" title="Warning">Visit Example Site</a>

The warning will appear as tooltip when link is hovered over.

**Comment by ItshMoh** [comment]
> > > @ItshMoh, i don't think external link should open in the same window, instead we should let users know it opens a new window as indicated in the issue :)
> > 
> > 
> > Hey @AceTheCreator Do you want the message for opening to the new window like this. alert_new_window_react Here when user clicks the link it will get alert notifcations.
> 
> @ItshMoh, it doesn't have to be an alert, you can just add the warning message inside the title attribute like this:
> 
> [Visit Example Site](https://example.com)
> 
> The warning will appear as tooltip when link is hovered over.

Hey @AceTheCreator  i have added the tooltip on hovering over the button. 
react_open_new_window

**Review by AceTheCreator — APPROVED** [review]
LGTM!

**Pull request merged**
