### PR TITLE
refactor: add an optional chain instead of an expression check

### LINKED ISSUE #779: Prefer using an optional chain expression instead, as it's more concise and easier to read.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLpgi9mf_H5ePyyC&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLpgi9mf_H5ePyyC&tab=code

### PR DESCRIPTION
**Pull request by syedzubeen**
**Description**

Changes proposed in this pull request:

Added an optional chain instead of an expression check

**Related issue(s)**
Fixes #779

### CODE REVIEW

**Comment by derberg** [comment]
@syedzubeen Thanks for the PR. When you contribute to any project, especially open source, you should open a PR only once you are familiarized with contributing guide like https://github.com/asyncapi/asyncapi-react/blob/master/CONTRIBUTING.md

- please adjust your PR title:
   - use [imperative mood](https://cbea.ms/git-commit/#imperative) in PR title
   - use proper conventional commits prefix (you have a bot comment with details - in your case it is `refactor`

**Comment by syedzubeen** [comment]
Updated.

**Review by derberg — CHANGES_REQUESTED** [review]
please check out linter complains

```
> lint
> tslint -c ./tslint.json --project tsconfig.base.json --format verbose && prettier --check "**/*.{ts,tsx,js,jsx,json,html,css,yaml}"

Checking formatting...
library/src/containers/Messages/MessageExample.tsx
Code style issues found in the above file(s). Forgot to run Prettier?
Error: Process completed with exit code 1.
```

**Comment by derberg** [comment]
closing as no followup

**Pull request closed without merging**
