### PR TITLE
fix: handled the document object being undefined in the parser result.

### PR DESCRIPTION
**Pull request by ashmit-coder**
**Description**

Changes proposed in this pull request:

- Handled the document object being undefined.
- In the changes proposed the code section throws an error when the document object is undefined.

**Related issue(s)**

Fixes:  #874

### CODE REVIEW

**Comment by ashmit-coder** [comment]
Hey @magicmatatjahu or @derberg I was enhancing the error message but am unable to apply any css to the above text that is being rendered

**Comment by ashmit-coder** [comment]
Also I would like to know if this is an upstream error or we should handle it here itself and make changes as per the latest state of the parser output

**Comment by derberg** [comment]
can you update PR with latest master, and resolve conflicts please 🙏🏼

**Comment by ibishal** [comment]
> can you update PR with latest master, and resolve conflicts please 🙏🏼

cc @ashmit-coder

**Comment by derberg** [comment]
no response in 2 weeks.

closing the PR. @ashmit-coder feel free to open a new PR with resolved conflicts. I'm just closing it for cleanup purposes to not have open and not active PR open forever

**Comment by ashmit-coder** [comment]
> no response in 2 weeks.
> 
> closing the PR. @ashmit-coder feel free to open a new PR with resolved conflicts. I'm just closing it for cleanup purposes to not have open and not active PR open forever

Hey sorry @derberg I was busy with other stuff. I will try to create a new PR during the GSOC period itself.

**Pull request closed without merging**
