### PR TITLE
refactor: add sidebar and render examples

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:

> As in previous PRs, this only focus on code, not styling - it will be done in asyncapi/shape-up-process#86

- Add Sidebar component with navigation like in HTML-Template with `sidebarOrganization` logic.
- Render examples for messages.

Examples:

image

**Related issue(s)**
Part of https://github.com/asyncapi/shape-up-process/issues/87
See also (fix) https://github.com/asyncapi/html-template/issues/15

### CODE REVIEW

**Comment by derberg** [comment]
oh 2 features in one pr 😅 

- dummy spec should always be in sync with the one in generator, avoided having custom copy and modify the original file
- some code and tests were remove, new code showed up, for examples, and it is not tested
- screen shot in description shows the text is not wrapped and overlaps main content

**Comment by magicmatatjahu** [comment]
@derberg Thanks for review! Hah 😅 Yes 2 features, but one missed in previous PRs with examples for messages and one totally new in component with sidebar. This is last PR with "new" things, next will be focused on styling.

> dummy spec should always be in sync with the one in generator, avoided having custom copy and modify the original file

I removed in last commit changes from `dummy.yaml`, but I had to check if everything works with `sidebarOrganization` logic  like in HTML-Template - dummy spec hasn't appropriate data for that.

> some code and tests were remove, new code showed up, for examples, and it is not tested

I added tests, sorry 😅 

> screen shot in description shows the text is not wrapped and overlaps main content

Yep, I know, this PR (like previous) only focus on code and as you see there are 600 changed LOC. Next PRs will be focused on styling. I wanna split styling to 3 PRs: Info + Servers, Operations + Messages, Sidebar + missed parts.

Could you look again? Thanks from the mountain! 🤣

**Comment by derberg** [comment]
> I removed in last commit changes from dummy.yaml, but I had to check if everything works with sidebarOrganization logic like in HTML-Template - dummy spec hasn't appropriate data for that.

PR's are welcome 😄

**Review by derberg — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@derberg Thanks!

**Pull request merged**
