### PR TITLE
Add Gitpod support 🧡

### PR DESCRIPTION
**Pull request by pawlean**
**Description**

Hi Async API folks! Pauline from Gitpod here. I've been lurking around the project for the last few days looking at ways I can contribute. After my live stream with [Alejandra](https://www.youtube.com/watch?v=vJy3lBs08Oo), I was keen to learn more!

This PR will add Gitpod support, allowing folks to just start a Gitpod workspace instantly and start contributing! 

Changes proposed in this pull request:

- Add [Gitpod](https://gitpod.io/) Support

**Related issue(s)**

Start a dev environment instantly to review this PR [here](https://gitpod.io/#https://github.com/asyncapi/asyncapi-react/pull/476).

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@pawlean Hello! On `master` branch we have old version fo component, you should create PR for the `next` branch https://github.com/asyncapi/asyncapi-react/tree/next :)

**Comment by Samridhi-98** [comment]
@magicmatatjahu  I would like to work on it if this PR is dead and the issue is still active.

**Comment by magicmatatjahu** [comment]
@Samridhi-98 Hi! this is not an issue, but a contribution from @pawlean :) Let @pawlean comment on this, if you can take it :)

**Comment by derberg** [comment]
@Samridhi-98 go-ahead please 🙏🏼

**Pull request closed without merging**
