### PR TITLE
refactor: migrate from tslint to eslint

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

Changes proposed in this pull request:

- migrate from tslint to eslint

**Related issue(s)**

See also #891

### CODE REVIEW

**Comment by kennethaasan** [comment]
@derberg, please review. I know it's a lot of changes, but it's kind of necessary in this PR. I added some strict TS rules because this repo has way too much use of any. That should be the exception and not the norm.

**Comment by derberg** [comment]
lgtm, just thinking if we really need a release, `refactor: ` should be fine imho

**Comment by kennethaasan** [comment]
@derberg, I was unsure myself. Let's do refactor

**Review by derberg — APPROVED** [review]

**Pull request merged**
