### PR TITLE
fix: changed the Navigation tab functionality

### PR DESCRIPTION
**Pull request by ItshMoh**
**Description**
Fixed the navigation problem in NavBar.

**Related issue(s)**
fixes: #1008 
[Screencast from 16-09-24 09_25_04 PM IST.webm](https://github.com/user-attachments/assets/6236f148-d9b3-4173-9d43-253aa86f86a1)

### CODE REVIEW

**Comment by ItshMoh** [comment]
@derberg @AceTheCreator can you please review my pr?

**Review by AceTheCreator — APPROVED** [review]
LGTM! 🚀

**Comment by AceTheCreator** [comment]
@ItshMoh, can you kindly update your branch?

**Comment by ItshMoh** [comment]
> @ItshMoh, can you kindly update your branch?

@AceTheCreator  Updated the branch.

**Pull request merged**
