### PR TITLE
fix: update isomorphic-dompurify and remove @types/highlight.js

### PR DESCRIPTION
**Pull request by batyshkaLenin**
Changes proposed in this pull request:

- Remove @types/highlight.js, because highlight.js have own type definitions
- Update isomorphic-dompurify and @types/dompurify

### CODE REVIEW

**Comment by derberg** [comment]
@batyshkaLenin thanks, can you share why these updates : `Update isomorphic-dompurify and @types/dompurify` are needed?

**Comment by batyshkaLenin** [comment]
@derberg @types/highlight.js I removed because this library has its own type declarations. isomorphic-dompurify I updated because, every time I installed dependencies in my project, there was a warning that one of its dependencies had a CVE (I don't remember which one, I made this PR over two weeks ago). @types/dompurify I updated to not have conflicting type versions in package-json, because isomorphic-dompurify has a different type version. In a broader view, there was no big need to upgrade, I wanted to get rid of the warning when installing dependencies in my project.

**Review by derberg — APPROVED** [review]
Thanks, since we update dev dependency, we should release patch, this is why I changed the prefix to `fix:`

**Pull request merged**
