### PR TITLE
feat: update openapi-sampler to 1.0.0 for better examples generation

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:

Update `openapi-sampler` package to `1.0.0`. Support for more type formats and JSON Schema 7 driven by support for OpenAPI 3.1.
Changes: https://github.com/Redocly/openapi-sampler/pull/122

Displaying `time` format:

image

**Related issue(s)**
Part of https://github.com/asyncapi/asyncapi-react/issues/209

### CODE REVIEW

**Comment by derberg** [comment]
@magicmatatjahu I took the liberty to extend description a bit and the PR title too.

You need to change to merge into master and not next

**Comment by magicmatatjahu** [comment]
@derberg Thanks! I described why it must be done in two separate PRs here -> https://github.com/asyncapi/asyncapi-react/pull/352#issuecomment-848633240 It's related to changes in package-lock between master and next branches. If I will make cherrypick from master to next then I will have to fixing rebase issues.

**Comment by derberg** [comment]
@magicmatatjahu sorry but I didn't get it. what is the problem to put it into master, then merge master into next? even if there are differences with conflicts, then just resolve by saying what is in next is priority, then `npm install` to add updated openapi-sampler to package-lock. Or am I missing something?

**Comment by magicmatatjahu** [comment]
Then you will have two different commits if you will change something from cherry picking, yes? It will only complicate topic, really.

**Comment by derberg** [comment]
Do you mean cherry-picking as a concept or as a git functionality? why not just do a simple merge of latest master into next? I don't think there is anything in the master that cannot be pulled into next, right? this means normal PR, with as many commits you want and then squashing and merging into `next` as a single commit, right?

**Comment by derberg** [comment]
🤦🏼 I think now I get it, of course you need to do cherry pick, you are right that 2 separate PRs to next and master are better. Awaiting for a PR to master then

**Comment by magicmatatjahu** [comment]
> why not just do a simple merge of latest master into next? I don't think there is anything in the master that cannot be pulled into next, right?

No, there are a lot of changes between master and next branches. As I remember some dependencies also was removed from next branches in unification time. Really, don't complicated topic in this area. We will have to merge master to next in some time, when we will decide to go finally with `1.0.0`, but it's not worth the trouble for just one package.

**Review by derberg — APPROVED** [review]

**Comment by magicmatatjahu** [comment]
@derberg Thanks a lot for patience ❤️

**Comment by derberg** [comment]
@magicmatatjahu remember about it once we see each other in a bar 🍻 😆

**Pull request merged**
