### PR TITLE
refactor: add optional chain instead of expression

### LINKED ISSUE #778: Prefer using an optional chain expression instead, as it's more concise and easier to read.
## Why this issue?
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLpgi9mf_H5ePyyB&tab=why

## Where's the issue? 
https://sonarcloud.io/project/issues?resolved=false&id=asyncapi_asyncapi-react&open=AYrVnLpgi9mf_H5ePyyB&tab=code

### PR DESCRIPTION
**Pull request by syedzubeen**
**Description**

Add optional chain instead of an expression

**Related issue(s)**
Fixes #778

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Thanks!

**Comment by derberg** [comment]
@syedzubeen please run linter locally and fix related issue as now merging is not possible

**Comment by derberg** [comment]
@syedzubeen do you need some help with your PRs?

**Comment by parasss19** [comment]
> @syedzubeen do you need some help with your PRs?

Can i work on this issue?

**Comment by derberg** [comment]
@parasss19 I guess so, seems like @syedzubeen is no longer interested with this one

**Comment by parasss19** [comment]
> @parasss19 I guess so, seems like @syedzubeen is no longer interested with this one

hey  @derberg i added the optional chain but there are many lint error and im not understanding it

Screenshot 2023-10-16 225805

**Comment by derberg** [comment]
Closing as looks like at the moment it is not clear how to fix this topic

**Pull request closed without merging**
