### PR TITLE
feat: support AsyncAPI 2.5.0

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

Changes proposed in this pull request:

Support AsyncAPI 2.5.0:
- render tags in Server Object

image

**Related issue(s)**
Part of https://github.com/asyncapi/spec/issues/830

### CODE REVIEW

**Comment by derberg** [comment]
as separate issue we will handle discussion if we should enable grouping of servers by tag in documentation? like it is with operations?

**Review by derberg — APPROVED** [review]
don't forget to create followup issue 😉

**Comment by magicmatatjahu** [comment]
@derberg https://github.com/asyncapi/asyncapi-react/issues/649 :)

**Pull request merged**
