### PR TITLE
chore:renamed App component to Playground issue #144

### PR DESCRIPTION
**Pull request by JakubIwanowski**
**Description**
Renamed App component file to Playground. Changed references to that file in other files(index.tsx)

**Related issue(s)**
issue #144

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]
@JakubIwanowski Thanks for contribution! Please check also others issues in this and in others repositories in our org. Happy Hacktoberfest!

**Comment by magicmatatjahu** [comment]
@all-contributors please add @JakubIwanowski for code

**Comment by JakubIwanowski** [comment]
> @JakubIwanowski Thanks for contribution! Please check also others issues in this and in others repositories in our org. Happy Hacktoberfest!

Will do! Happy Hacktoberfest!

**Comment by derberg** [comment]
@JakubIwanowski would you mind sharing with me how did you find out about AsyncAPI and this issue? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

**Pull request merged**
