### PR TITLE
fix: render schema title if it exists

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

Changes proposed in this pull request:

- Fix for https://github.com/asyncapi/asyncapi-react/pull/744#discussion_r1433826404

**Related issue(s)**

Fixes bug introduced in #744

### CODE REVIEW

**Comment by kennethaasan** [comment]
@jonaslagoni @derberg, please review.

**Comment by jonaslagoni** [comment]
@kennethaasan I am not codeowner here 🙂

**Comment by kennethaasan** [comment]
@jonaslagoni, ups sorry.

@magicmatatjahu @derberg @fmvilas, please review. This blocks us from upgrading `asyncapi-react`.

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Pull request merged**
