### PR TITLE
feat!: upgrade to react v18

### PR DESCRIPTION
**Pull request by kennethaasan**
**Description**

Changes proposed in this pull request:

- upgrades react to v18 by following https://legacy.reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

**Related issue(s)**

See also #891

### CODE REVIEW

**Comment by derberg** [comment]
@kennethaasan one tiny merge conflict because of https://github.com/asyncapi/asyncapi-react/pull/995

**Comment by kennethaasan** [comment]
@derberg, should be fixed now.

**Comment by derberg** [comment]
and you checked and playground still works after upgrade? 😄

**Pull request merged**
