### PR TITLE
docs: update the command to install the component

### PR DESCRIPTION
**Pull request by m1ner79**
I was using the original command npm install --save @asyncapi/react-component when doing research for my article and I had some issues which were resolved but only when I requested senior dev to look at it.

It is more likely due to my inexperience but there are other junior developers like myself who may not know to use npm install --save @asyncapi/react-component@next command.

To make juniors life easier, may I ask to merge this request into your branch?

Thank you.

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@m1ner79 Right, good catch! Can't believe we had such a big bug in docs 🤦🏼‍♂️  Thanks a lot!

**Comment by magicmatatjahu** [comment]
@m1ner79 One additional thing, could you also update that installation guide https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/web-component.md#installation to the:

```bash
npm install --save @asyncapi/web-component@next
```

**Comment by m1ner79** [comment]
> @m1ner79 One additional thing, could you also update that installation guide https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/web-component.md#installation to the:
> 
> ```shell
> npm install --save @asyncapi/web-component@next
> ```
> 
> Thanks!

That's now done, as per request.

**Review by magicmatatjahu — APPROVED** [review]
@m1ner79 LGTM! Thanks very much for PR! :)

**Comment by magicmatatjahu** [comment]
@all-contributors add @m1ner79 for docs

**Pull request merged**
